/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
  public String getGreeting() {
    return "Welcome to my solutions!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    Lab10 lab10 = new Lab10();
    /* test uppgift 6 */
    int[] arr = {12, 13, 14, 13, 0, 0, 15, 15, 0, 13};
    lab10.bubbleSortData(arr);
    /* test uppgift 7 */
    int[][] test1 = {{1, 2, 3}, {4, 5, 6}};
    int[][] test2 = {{6, 5, 8}};
    int[][] test3 = {{5, 1, 21}, {3, 63, 6}};
    // int[][] ans = lab10.compareEntries(test1, test3);
    /*
     * for (int i = 0; i < ans.length; i++) {
     * for (int j = 0; j < ans[i].length; j++) {
     * System.out.println(ans[i][j]);
     * }
     * }
     */

    /* test uppgift8 */

    int[] arr2 = {12, 13, 14, 13, 4, 6, 15, 87, 0, 1};
    int[] answer = lab10.insertionSortData(arr2);

    for (int i : answer) {
      System.out.println("insertion sorted data: " + i);
    }

    /* test uppgift9 */
    /*
     * int[][] arr3 = {{1, 1, 2, 3, 3}, {2, 1, 1, 2, 3}, {3, 2, 2, 1, 2}, {3, 3, 3,
     * 3, 3}};
     * boolean[][] ans = lab10.survivalGame(arr3);
     * for (int i = 0; i < ans.length; i++) {
     * for (int j = 0; j < ans[i].length; j++) {
     * System.out.println("row: " + i + " col: " + j + " value: " + ans[i][j]);
     * }
     * }
     */

    /* test uppgift10 */
    Scanner scan = new Scanner(System.in);
    lab10.dentistReception(scan);
  }
}
